[tool.ruff]
select = ["ANN", "B", "D", "E", "F", "W", "S", "T20", "PTH", "TD"]
ignore = ["E501", "D210", "S101", "D204", "D203", "D212"]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
ignore_missing_imports = true