"""
Author: Alex Cannan
Date Created: 4/23/20
Purpose: This file will hold the SourceNode class, which is the smallest object
in the source tree generated by this package
"""

from urllib.parse import urlparse

from newspaper import Article


def get_url_base(url):
    return urlparse(url).netloc


def read_blacklist():
    with open('blacklist.txt', 'r') as f:
        blacklist = []
        for line in f:
            blacklist.append(line.lstrip().rstrip())
        while '' in blacklist:
            blacklist.remove('')
        return blacklist


class SourceNode:
    def __init__(self, url, parent=None):
        self.url = url
        self.links = []
        self.parents = [parent]
        self.children = []
        self.scan_level = 0

    def get_links(self):
        print("Parsing", self.url)
        try:
            article = Article(self.url)
            article.download()
            article.parse()
            self.links = article.links
        except Exception as e:
            print("Failed to parse", self.url)
            print(e)

    def filter_links(self, ignore_local=True, check_blacklist=True):
        local_base = get_url_base(self.url)
        good_links = []
        blacklist = read_blacklist()
        for link in self.links:
            link_good = True
            base = get_url_base(link)
            if ignore_local and base == local_base:
                link_good = False
            for badurl in blacklist:
                if badurl in base:
                    link_good = False
            if base == '':
                link_good = False
            if link_good:
                good_links.append(link)
        self.links = good_links


if __name__ == '__main__':
    print(read_blacklist())
